### ISSUE TITLE
How to delete access key?

### ISSUE THREAD

**Issue by ghost** [7vlad7/python-outline#2]
Как удалить access_key? 
from outline.client import OutlineClient

client = OutlineClient(base_url="https://*******/secret")

client.delete_key(access_key='ss://secret@********/?outline=1')
Выбивает в ошибку
Traceback (most recent call last):
  File "C:\Users\Der4ik0\PycharmProjects\pythonProject2\main.py", line 6, in <module>
    client.delete_key(access_key=трали вали/?outline=1')
  File "C:\Users\Der4ik0\AppData\Roaming\Python\Python311\site-packages\outline\client.py", line 283, in delete_key
    r.raise_for_status()
  File "C:\Users\Der4ik0\AppData\Roaming\Python\Python311\site-packages\httpx\_models.py", line 759, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '404 Not Found' for url

(ключ и ссылка замены дабы не забрал кто)

**Comment by ghost** [comment]
Traceback (most recent call last):
  File "C:\Users\Der4ik0\PycharmProjects\pythonProject2\main.py", line 6, in <module>
    client.key(access_key='/?outline=1')
  File "C:\Users\Der4ik0\AppData\Roaming\Python\Python311\site-packages\outline\client.py", line 264, in key
    raise OutlineAccessKeyNotFound()
outline.exceptions.OutlineAccessKeyNotFound: Access key not found
Или вот

**Comment by 7vlad7** [comment]
@Der4ik0 access_key принимает id ключа
